sudo: required

language: bash

services:
  - docker
before_install:
  - sudo apt-get update
  - docker-compose -v
  - docker-compose build 

before_script:
  - docker-compose run --rm tests
  # push test image to ECR
  - docker pull quay.io/keboola/developer-portal-cli-v2:latest
  - export REPOSITORY=`docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP`
  - docker tag $APP_IMAGE:latest $REPOSITORY:test
  - eval $(docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP)
  - docker push $REPOSITORY:test
  - docker pull quay.io/keboola/syrup-cli:latest

script:
  - docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job $KBC_DEVELOPERPORTAL_APP $KBC_APP_TEST_CONFIG test

after_success:
  - docker-compose run --rm codeclimate-test-reporter
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true

notifications:
  email: false
  slack:
    secure: Z9kbxFPXracnOKEi8Nspyuz0QkPgPssfKdEXSOk/5HdJ6bg2mwFaqFNvZVQ8eLxqkDSKxHuYuKdlFwriuo/54ReSXpacipbLD9nRzuoNSlLEjofSEjArtjmf+qkAAOFfXEIk3JflGXhyKa7fbtGcsWcLAeUwL/RYxq1nKKhUs9e0s8KpZnbNOI7T3C9LHf3F7eqgQajazIZibEhEqFZGsZ2ttmDk3pylvwNFOMl+qARscaQ9EumbO9o0xPUmUCAnSq1qFh+aKUy8ZnFshpTKnsNZm0T6iFNdITQtjCuN1aGgM2wA3Myx+hbubNwbZEJdz7oeYezHwbf2TPkNcQiIO+/hFSTR+uAbHHOwE4j4Gx1SwG6PRJHV0v6Ava2KMdVrW9oFwQ7JApEeX+jdMSSqMZsIHhwngawc3OhNe6Y4Kgx9n1s6PnV6AQA/Dxlf0EzTftccCNshC3yOl5HIHNdN5/iGIrjxFLvQD6ZaUhpfNH3Fg5HdldPc+m0o8aJEgho9HCg8RyWGJsWB1uO+vESNr/F/OWhpLPyQFyvEoh2MV4R6Pvu2ZNMx1FBGuA8yFct41xNHAuJPxPUjin5yemAn7zLJ+UegFbsDmfcSi4nts6wLEQdZpBht4Lei7cJ5KPITR/XiJKNbkE5UOdZOc+i7fbyxUSVsD1vSy6ZnEb9WjwU=
