sudo: required

language: bash

services:
  - docker
before_install:
  - sudo apt-get update
  - docker-compose -v
  - docker-compose build 

before_script:
  - docker-compose run --rm tests
  # push test image to ECR
  - docker pull quay.io/keboola/developer-portal-cli-v2:latest
  - export REPOSITORY=`docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP`
  - docker tag $APP_IMAGE:latest $REPOSITORY:test
  - eval $(docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP)
  - docker push $REPOSITORY:test
  - docker pull quay.io/keboola/syrup-cli:latest

script:
  - docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job $KBC_DEVELOPERPORTAL_APP $KBC_APP_TEST_CONFIG test

after_success:
  - docker-compose run --rm codeclimate-test-reporter
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true

notifications:
  email: false
  slack:
    secure: ep8SjWLZHaiShTQmskPTiO3ST9SR6kQQf2YlPara+lGSyvHWWFQYItSDJitKmCu7q9dIJz3g40geRGNyfR0+u1UiWTwQO2vGIP+tCRoRjubA2qT7cdbqbEX8uazqkMxU/ldfWQHEErBNpngGdkp75U9/ttaOFf6ZQNNehzliZmE123HP3K2Wa4w+kt/6inF6BaSjiw+dw5sEH0/swXBQ567BthPz8KGxi62tJ4VsBHZCmyz50b3H6qZO4T2k4N8yJcF8gDnuLYgtDun6sukPlbkoOxi4cKFZoqM2t+qZ+oM4juCmzddj6zsqrgKBBuBWrXmaMEg56fjjM4urMFHtG3drwowAFiOfCR7BidQsaaYBNcre0SPcpM+dcwHz7znWmz9AZPWJQJGEoiPSHVnQFzB+Y49LWmJyIgnrCgQKTEFbysoVSN/asvWDEftiijIhpSPWxm9qsTZrLg1q7mEq4kmd6YYPeALZXpvfKrql93A7UGIRjM/ZTTdVcOFTU96yOc91JcvATbmK/kbrgjKq9vmna0Jih/xAshNlGAAgYLSF7f6RdoVYphICr+BfgglcAbLSIghLlZvgnPkpd45ELHenM+5o4O9IcFJiRKxQox/TAMD4utqdrZ10AwuP4oZzGI98Xd8zyA/7McihBMvuDCjkQrezw9W3IYu/m3C0SKI=
