version: '2'
services:
  tests:
    build: .
    image: keboola/google-bigquery-writer
    command: sh -c '/home/tests.sh'
    environment:
      - OAUTH_ACCESS_TOKEN
      - OAUTH_CLIENT_ID
      - OAUTH_CLIENT_SECRET
      - OAUTH_REFRESH_TOKEN
      - SERVICE_ACCOUNT_PRIVATE_KEY
      - SERVICE_ACCOUNT_CLIENT_EMAIL
      - BIGQUERY_PROJECT
      - BIGQUERY_DATASET
      - BIGQUERY_TABLE
    volumes:
      - ./:/home
  codeclimate-test-reporter:
    build: .
    image: keboola/google-bigquery-writer
    command: sh -c 'pip install codeclimate-test-reporter && codeclimate-test-reporter --file .coverage'
    environment:
      - CODECLIMATE_REPO_TOKEN
    volumes:
      - ./:/home      
